### PR TITLE
feat: support variables

### PR DESCRIPTION
**Pull request by fjogeleit**
* proposal to mock/support variables from external sources like ConfigMaps
* Split Context field in Context and Variables
* Load Variables into JSONContext

Bildschirmfoto 2023-05-13 um 10 48 12

Bildschirmfoto 2023-05-13 um 10 49 10

### CODE REVIEW

**Comment by eddycharly** [comment]
Looks good !

**Comment by eddycharly** [comment]
Maybe this should be done per policy/rule (variables are specific to a rule).

**Comment by fjogeleit** [comment]
in general right is right but if we consider effort and benefit - a simple solution is better than not supporting it at all. I just don't know of any solution that is easy to support or visualize.

**Comment by eddycharly** [comment]
agree, we can always improve later if needed

**Pull request merged**
