### PR TITLE
feat: structure backend in packages

### PR DESCRIPTION
**Pull request by fjogeleit**
* structure backend in packages
* add tests for loading and processing

### CODE REVIEW

**Comment by eddycharly** [comment]
I thought about reorganising the backend code too ;-)

**Comment by fjogeleit** [comment]
are you fine with the current proposal? We can also change it later on, if you see improvements

**Comment by eddycharly** [comment]
I'm not sure i would have adopted this organisation but we can always change later.

**Comment by fjogeleit** [comment]
okay, sure. Yeah just a starting point. Then I can continue with the TUF staff and config support

**Comment by eddycharly** [comment]
> TUF staff

What's that ?

**Comment by eddycharly** [comment]
> config support

TBH i'm not sure we want to bring this to the frontend

**Comment by fjogeleit** [comment]
> okay, sure. Yeah just a starting point. Then I can continue with the TUF staff and config support

TUF_ROOT needs to be a writeable volume for keyless image verification and with config I mean the Kyverno config

**Pull request merged**
